export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const UPDATE_AUTH_USER = "UPDATE_AUTH_USER";
export const UPDATE_LOAD_USER = "UPDATE_LOAD_USER";

export const SEND_NEW_CHAT_MESSAGE = "SEND_NEW_CHAT_MESSAGE";
export const SEND_NEW_MEDIA_MESSAGE = "SEND_NEW_MEDIA_MESSAGE";
export const RECEIVE_NEW_MEDIA_MESSAGE = "RECEIVE_NEW_MEDIA_MESSAGE";
export const SET_CHAT_USERS = "SET_CHAT_USERS";
export const RECEIVE_NEW_CHAT_MESSAGE = "RECEIVE_NEW_CHAT_MESSAGE";
export const SET_CONVERSATION_DATA = "SET_CONVERSATION_DATA";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_MATCH_USERS = "SET_MATCH_USERS";
export const DELETE_MATCH = "DELETE_MATCH";
export const SET_SELECTED_MATCH = "SET_SELECTED_MATCH";

export const SET_USERS = "SET_USERS";
export const SET_MATCH_USER = "SET_MATCH_USER";
export const SET_CHAT_LIST = "SET_CHAT_LIST";
