export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const UPDATE_AUTH_USER = "UPDATE_AUTH_USER";
export const UPDATE_LOAD_USER = "UPDATE_LOAD_USER";
